# Generated by Django 5.1 on 2024-10-18 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestart', models.TimeField()),
                ('TimeEnd', models.TimeField()),
                ('Day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100)),
                ('RegisteredDate', models.DateTimeField(auto_now_add=True)),
                ('SessionType', models.CharField(choices=[('Tutorial', 'Tutorial'), ('Lecture', 'Lecture'), ('Lab', 'Lab'), ('Discussion', 'Discussion'), ('Presentation', 'Presentation')], max_length=100)),
                ('CourseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coursename')),
                ('Instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.timetablemain')),
                ('Venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venue')),
            ],
        ),
    ]
